### ISSUE TITLE
polysharp dont generate source

### ISSUE THREAD

**Issue by singsong2016** [Sergio0694/PolySharp#43] opened 2023-01-16 01:15 UTC
in my netframework4.8 console project, after added reference to polysharp, and set language version to C#11.0, there is no source file generated, and when i use required and init in my code, there is build error occured

**Comment by drivardxrm** [comment] 2023-01-16 03:09
I have the same issue with a .net framework 4.6.2 class library (and console app). 
I have tried with a NET Core 3.1 project without any problems.

It seems that the source generators assembly doesn't get registered in the analyzers section of the project.

It's probably not recommended, but I was able to make it work by adding the reference manually to PolySharp.SourceGenerators.dll

1- Add Analyzer
![image](https://user-images.githubusercontent.com/38399134/212585971-ca1bcdd1-abfb-449a-a267-90504161dd4c.png)

2- Navigate to the package of the project and add a reference to PolySharp.SourceGenerators.dll
![image](https://user-images.githubusercontent.com/38399134/212585401-fe9ff320-1edc-4575-acfd-85d91ad521b6.png)

![image](https://user-images.githubusercontent.com/38399134/212585784-7ab8c1d5-a744-4b51-87d4-7decd51b710e.png)

After that it worked flawlessly for me.

Only problem with this is that the version doesn't get updated when there is a package update and I need to re-add the reference the newest dll.

Hope this could help to pinpoint the problem.

**Comment by Sergio0694** [comment] 2023-01-16 10:49
Seems like a duplicate of #39. You'll need to switch to using an [SDK-style .csproj project](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/overview) 🙂
Source generators are not supported with legacy style NETFX projects and will not be loaded correctly.

**Closed by Sergio0694** 2023-01-16 10:49 UTC
