### ISSUE TITLE
Does PolySharp support multitargeting?

### ISSUE THREAD

**Issue by sungam3r** [Sergio0694/PolySharp#48] opened 2023-01-16 16:46 UTC
I recently saw this package and decided to try.

Config:
```xml
<PackageReference Include="PolySharp" Version="1.10.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

Output:
![изображение](https://user-images.githubusercontent.com/21261007/212728763-3dc66275-674c-48da-a87c-51d7bfc1b0b7.png)

If I change reference to
```xml
 <PackageReference Include="PolySharp" Version="1.10.0" Condition="'$(TargetFramework)' != 'net5' AND '$(TargetFramework)' != 'net6' AND '$(TargetFramework)' != 'net7'">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
```

then there are no errors.

I would like PolySharp does not require Conditional attribute on TFMs where all necessary attributes are present.

**Comment by Sergio0694** [comment] 2023-01-16 17:00
PolySharp already supports this (eg. I'm personally using already in several multi-targeted projects, like you can see here: https://github.com/Sergio0694/ComputeSharp/pull/471). I'm not entirely sure what's going on here. Are you able to provide a minimal repro?

**Comment by Shane32** [comment] 2023-01-16 17:04
Maybe this has more to do with multiple projects rather than multiple targets.  Is the injected code `internal`?

**Comment by Sergio0694** [comment] 2023-01-16 17:05
> "Is the injected code internal?"

@Shane32 it is by default, yes, unless you explicitly set the "PolySharpUsePublicAccessibilityForGeneratedTypes" property.

**Comment by Shane32** [comment] 2023-01-16 17:13
@Sergio0694 It may be due to the fact that the test project, where the build is failing, has references to two different projects both of which utilize InternalsVisibleTo back towards the test project...

**Comment by Sergio0694** [comment] 2023-01-16 17:19
Ah, yeah that makes sense. If the test project is, say, targeting .NET 6 (which has the attribute), but is referencing a project on, say, the .NET Standard 2.0 project, that project will have `IsExternalinit` generated for it, but then `InternalsVisibleTo` will make that give visibility to the test project as well, which now has two versions of that attirbute... I guess that could be possible 🤔

**Comment by Shane32** [comment] 2023-01-16 17:20
Attempting to reproduce now.......

**Comment by Sergio0694** [comment] 2023-01-16 17:21
Anyway if the issue is in a test project this definitely doesn't seem related to PolySharp per se. The library is correctly generating only the polyfills that are needed on each TFM, if then this specific repo has some weird configuration with test projects and `InternalsVisibleTo` settings caausing this issue in a separate project, this seems like a different issue 😅

Closing this for now, happy to reopen in case more info is provided that links this to an actual issue in PolySharp 🙂
I assume for that project, adding the condition on the `PackageReference` seems like an easy enough workaround at least.

**Closed by Sergio0694** 2023-01-16 17:21 UTC
Labels: needs more info

**Comment by Shane32** [comment] 2023-01-16 18:17
FYI, below is a sample.  Removing `PolySharp` from the console app, or setting the TFM for ClassLibrary1 to `netstandard2.0;net5.0`, adding a condition to prevent `PolySharp` from being included on .NET 5+ "solves" the issue.

## ClassLibrary1

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>11</LangVersion>
	</PropertyGroup>

	<ItemGroup>
		<InternalsVisibleTo Include="ConsoleApp1" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="PolySharp" Version="1.10.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
```

```cs
namespace ClassLibrary1
{
    public class Class1
    {
    }
}
```

## ConsoleApp1

```xml
<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net7.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\ClassLibrary1\ClassLibrary1.csproj" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="PolySharp" Version="1.10.0">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
	</ItemGroup>

</Project>
```

```cs
// See https://aka.ms/new-console-template for more information
Console.WriteLine("Hello, World!");
```

**Comment by Nihlus** [comment] 2023-05-01 18:40
I've got the same issue with IsExternalInit, also in a test project that references another project in the same repository. It's likely to prevent the use of PolySharp as a replacement for IsExternalInit and Nullable in Remora.Sdk for the time being - see https://github.com/Remora/Remora.Results/pull/10 for the discussion.
